const validResponse = {
  state: 'SP',
  cities: [
    'EMBU',
    'VÁRZEA PAULISTA',
    'VARGEM GRANDE PAULISTA',
    'VARGEM',
    'TUIUTI',
    'TABOÃO DA SERRA',
    'SUZANO',
    'SÃO ROQUE',
    'SÃO PAULO',
    'SÃO LOURENÇO DA SERRA',
    'SÃO CAETANO DO SUL',
    'SÃO BERNARDO DO CAMPO',
    'SANTO ANDRÉ',
    'SANTANA DE PARNAÍBA',
    'SANTA ISABEL',
    'SALTO',
    'SALESÓPOLIS',
    'RIO GRANDE DA SERRA',
    'RIBEIRÃO PIRES',
    'POÁ',
    'PIRAPORA DO BOM JESUS',
    'PIRACAIA',
    'PINHALZINHO',
    'PEDRA BELA',
    'OSASCO',
    'NAZARÉ PAULISTA',
    'MORUNGABA',
    'MOGI DAS CRUZES',
    'MAUÁ',
    'MAIRIPORÃ',
    'MAIRINQUE',
    'JUQUITIBA',
    'JUNDIAÍ',
    'JOANÓPOLIS',
    'JARINU',
    'JANDIRA',
    'ITUPEVA',
    'ITU',
    'ITATIBA',
    'ITAQUAQUECETUBA',
    'ITAPEVI',
    'ITAPECERICA DA SERRA',
    'IGARATÁ',
    'GUARULHOS',
    'GUARAREMA',
    'FRANCO DA ROCHA',
    'FRANCISCO MORATO',
    'FERRAZ DE VASCONCELOS',
    'EMBU-GUAÇU',
    'DIADEMA',
    'COTIA',
    'CARAPICUÍBA',
    'CAMPO LIMPO PAULISTA',
    'CAJAMAR',
    'CAIEIRAS',
    'CABREÚVA',
    'BRAGANÇA PAULISTA',
    'BOM JESUS DOS PERDÕES',
    'BIRITIBA-MIRIM',
    'BARUERI',
    'ATIBAIA',
    'ARUJÁ',
    'ARAÇARIGUAMA',
    'ALUMÍNIO',
  ],
};

const validSortedAscResponse = {
  state: 'SP',
  cities: [
    'ALUMÍNIO',
    'ARAÇARIGUAMA',
    'ARUJÁ',
    'ATIBAIA',
    'BARUERI',
    'BIRITIBA-MIRIM',
    'BOM JESUS DOS PERDÕES',
    'BRAGANÇA PAULISTA',
    'CABREÚVA',
    'CAIEIRAS',
    'CAJAMAR',
    'CAMPO LIMPO PAULISTA',
    'CARAPICUÍBA',
    'COTIA',
    'DIADEMA',
    'EMBU',
    'EMBU-GUAÇU',
    'FERRAZ DE VASCONCELOS',
    'FRANCISCO MORATO',
    'FRANCO DA ROCHA',
    'GUARAREMA',
    'GUARULHOS',
    'IGARATÁ',
    'ITAPECERICA DA SERRA',
    'ITAPEVI',
    'ITAQUAQUECETUBA',
    'ITATIBA',
    'ITU',
    'ITUPEVA',
    'JANDIRA',
    'JARINU',
    'JOANÓPOLIS',
    'JUNDIAÍ',
    'JUQUITIBA',
    'MAIRINQUE',
    'MAIRIPORÃ',
    'MAUÁ',
    'MOGI DAS CRUZES',
    'MORUNGABA',
    'NAZARÉ PAULISTA',
    'OSASCO',
    'PEDRA BELA',
    'PINHALZINHO',
    'PIRACAIA',
    'PIRAPORA DO BOM JESUS',
    'POÁ',
    'RIBEIRÃO PIRES',
    'RIO GRANDE DA SERRA',
    'SALESÓPOLIS',
    'SALTO',
    'SANTA ISABEL',
    'SANTANA DE PARNAÍBA',
    'SANTO ANDRÉ',
    'SÃO BERNARDO DO CAMPO',
    'SÃO CAETANO DO SUL',
    'SÃO LOURENÇO DA SERRA',
    'SÃO PAULO',
    'SÃO ROQUE',
    'SUZANO',
    'TABOÃO DA SERRA',
    'TUIUTI',
    'VARGEM',
    'VARGEM GRANDE PAULISTA',
    'VÁRZEA PAULISTA',
  ],
};

const validSortedDescResponse = {
  state: 'SP',
  cities: [
    'VÁRZEA PAULISTA',
    'VARGEM GRANDE PAULISTA',
    'VARGEM',
    'TUIUTI',
    'TABOÃO DA SERRA',
    'SUZANO',
    'SÃO ROQUE',
    'SÃO PAULO',
    'SÃO LOURENÇO DA SERRA',
    'SÃO CAETANO DO SUL',
    'SÃO BERNARDO DO CAMPO',
    'SANTO ANDRÉ',
    'SANTANA DE PARNAÍBA',
    'SANTA ISABEL',
    'SALTO',
    'SALESÓPOLIS',
    'RIO GRANDE DA SERRA',
    'RIBEIRÃO PIRES',
    'POÁ',
    'PIRAPORA DO BOM JESUS',
    'PIRACAIA',
    'PINHALZINHO',
    'PEDRA BELA',
    'OSASCO',
    'NAZARÉ PAULISTA',
    'MORUNGABA',
    'MOGI DAS CRUZES',
    'MAUÁ',
    'MAIRIPORÃ',
    'MAIRINQUE',
    'JUQUITIBA',
    'JUNDIAÍ',
    'JOANÓPOLIS',
    'JARINU',
    'JANDIRA',
    'ITUPEVA',
    'ITU',
    'ITATIBA',
    'ITAQUAQUECETUBA',
    'ITAPEVI',
    'ITAPECERICA DA SERRA',
    'IGARATÁ',
    'GUARULHOS',
    'GUARAREMA',
    'FRANCO DA ROCHA',
    'FRANCISCO MORATO',
    'FERRAZ DE VASCONCELOS',
    'EMBU-GUAÇU',
    'EMBU',
    'DIADEMA',
    'COTIA',
    'CARAPICUÍBA',
    'CAMPO LIMPO PAULISTA',
    'CAJAMAR',
    'CAIEIRAS',
    'CABREÚVA',
    'BRAGANÇA PAULISTA',
    'BOM JESUS DOS PERDÕES',
    'BIRITIBA-MIRIM',
    'BARUERI',
    'ATIBAIA',
    'ARUJÁ',
    'ARAÇARIGUAMA',
    'ALUMÍNIO',
  ],
};

const invalidResponse = {
  type: 'ddd_error',
  message: 'DDD não encontrado',
  name: 'DDD_NOT_FOUND',
};

module.exports = {
  validResponse,
  invalidResponse,
  validSortedAscResponse,
  validSortedDescResponse,
};
