const validResponseV1 = {
  state: 'SP',
  cities: [
    'EMBU',
    'VÁRZEA PAULISTA',
    'VARGEM GRANDE PAULISTA',
    'VARGEM',
    'TUIUTI',
    'TABOÃO DA SERRA',
    'SUZANO',
    'SÃO ROQUE',
    'SÃO PAULO',
    'SÃO LOURENÇO DA SERRA',
    'SÃO CAETANO DO SUL',
    'SÃO BERNARDO DO CAMPO',
    'SANTO ANDRÉ',
    'SANTANA DE PARNAÍBA',
    'SANTA ISABEL',
    'SALTO',
    'SALESÓPOLIS',
    'RIO GRANDE DA SERRA',
    'RIBEIRÃO PIRES',
    'POÁ',
    'PIRAPORA DO BOM JESUS',
    'PIRACAIA',
    'PINHALZINHO',
    'PEDRA BELA',
    'OSASCO',
    'NAZARÉ PAULISTA',
    'MORUNGABA',
    'MOGI DAS CRUZES',
    'MAUÁ',
    'MAIRIPORÃ',
    'MAIRINQUE',
    'JUQUITIBA',
    'JUNDIAÍ',
    'JOANÓPOLIS',
    'JARINU',
    'JANDIRA',
    'ITUPEVA',
    'ITU',
    'ITATIBA',
    'ITAQUAQUECETUBA',
    'ITAPEVI',
    'ITAPECERICA DA SERRA',
    'IGARATÁ',
    'GUARULHOS',
    'GUARAREMA',
    'FRANCO DA ROCHA',
    'FRANCISCO MORATO',
    'FERRAZ DE VASCONCELOS',
    'EMBU-GUAÇU',
    'DIADEMA',
    'COTIA',
    'CARAPICUÍBA',
    'CAMPO LIMPO PAULISTA',
    'CAJAMAR',
    'CAIEIRAS',
    'CABREÚVA',
    'BRAGANÇA PAULISTA',
    'BOM JESUS DOS PERDÕES',
    'BIRITIBA-MIRIM',
    'BARUERI',
    'ATIBAIA',
    'ARUJÁ',
    'ARAÇARIGUAMA',
    'ALUMÍNIO',
  ],
};

const validResponseV2 = [
  {
    state: 'SP',
    cities: [
      'EMBU',
      'VÁRZEA PAULISTA',
      'VARGEM GRANDE PAULISTA',
      'VARGEM',
      'TUIUTI',
      'TABOÃO DA SERRA',
      'SUZANO',
      'SÃO ROQUE',
      'SÃO PAULO',
      'SÃO LOURENÇO DA SERRA',
      'SÃO CAETANO DO SUL',
      'SÃO BERNARDO DO CAMPO',
      'SANTO ANDRÉ',
      'SANTANA DE PARNAÍBA',
      'SANTA ISABEL',
      'SALTO',
      'SALESÓPOLIS',
      'RIO GRANDE DA SERRA',
      'RIBEIRÃO PIRES',
      'POÁ',
      'PIRAPORA DO BOM JESUS',
      'PIRACAIA',
      'PINHALZINHO',
      'PEDRA BELA',
      'OSASCO',
      'NAZARÉ PAULISTA',
      'MORUNGABA',
      'MOGI DAS CRUZES',
      'MAUÁ',
      'MAIRIPORÃ',
      'MAIRINQUE',
      'JUQUITIBA',
      'JUNDIAÍ',
      'JOANÓPOLIS',
      'JARINU',
      'JANDIRA',
      'ITUPEVA',
      'ITU',
      'ITATIBA',
      'ITAQUAQUECETUBA',
      'ITAPEVI',
      'ITAPECERICA DA SERRA',
      'IGARATÁ',
      'GUARULHOS',
      'GUARAREMA',
      'FRANCO DA ROCHA',
      'FRANCISCO MORATO',
      'FERRAZ DE VASCONCELOS',
      'EMBU-GUAÇU',
      'DIADEMA',
      'COTIA',
      'CARAPICUÍBA',
      'CAMPO LIMPO PAULISTA',
      'CAJAMAR',
      'CAIEIRAS',
      'CABREÚVA',
      'BRAGANÇA PAULISTA',
      'BOM JESUS DOS PERDÕES',
      'BIRITIBA-MIRIM',
      'BARUERI',
      'ATIBAIA',
      'ARUJÁ',
      'ARAÇARIGUAMA',
      'ALUMÍNIO',
    ],
  },
];

const validResponseAllDDDV1 = [
  {
    state: 'SP',
    ddds: ['19', '18', '14', '11', '16', '17', '15', '12', '13'],
  },
];

const validResponseDDDByStateV1 = [
  {
    ddd: '66',
    state: 'MT',
    cities: [
      'SANTO ANTONIO DO LESTE',
      'RONDOLANDIA',
      'NOVO SANTO ANTONIO',
      'NOVA CANÃA DO NORTE',
      'NOVA MONTE VERDE',
      'NOVA MARINGÁ',
      'NOVA GUARITA',
      'VILA RICA',
      'VERA',
      'UNIÃO DO SUL',
      'TORIXORÉU',
      'TESOURO',
      'TERRA NOVA DO NORTE',
      'TAPURAH',
      'TABAPORÃ',
      'SORRISO',
      'SINOP',
      'SERRA NOVA DOURADA',
      'SÃO FÉLIX DO ARAGUAIA',
      'SANTA TEREZINHA',
      'SANTA CRUZ DO XINGU',
      'RONDONÓPOLIS',
      'SÃO PEDRO DA CIPA',
      'SÃO JOSÉ DO XINGU',
      'SÃO JOSÉ DO POVO',
      'SANTA CARMEM',
      'RIBEIRÃOZINHO',
      'RIBEIRÃO CASCALHEIRA',
      'QUERÊNCIA',
      'PRIMAVERA DO LESTE',
      'POXORÉO',
      'PORTO DOS GAÚCHOS',
      'PORTO ALEGRE DO NORTE',
      'PONTE BRANCA',
      'PONTAL DO ARAGUAIA',
      'PLANALTO DA SERRA',
      'PEIXOTO DE AZEVEDO',
      'PEDRA PRETA',
      'PARANATINGA',
      'PARANAÍTA',
      'NOVO SÃO JOAQUIM',
      'NOVO HORIZONTE DO NORTE',
      'NOVO MUNDO',
      'NOVA XAVANTINA',
      'NOVA UBIRATÃ',
      'NOVA BRASILÂNDIA',
      'NOVA SANTA HELENA',
      'NOVA NAZARÉ',
      'NOVA BANDEIRANTES',
      'MATUPÁ',
      'MARCELÂNDIA',
      'LUCIÁRA',
      'JUSCIMEIRA',
      'JURUENA',
      'JUÍNA',
      'JUARA',
      'JACIARA',
      'ITAÚBA',
      'GUIRATINGA',
      'GUARANTÃ DO NORTE',
      'GENERAL CARNEIRO',
      'GAÚCHA DO NORTE',
      'FELIZ NATAL',
      'DOM AQUINO',
      'COTRIGUAÇU',
      'CONFRESA',
      'COLNIZA',
      'COLÍDER',
      'COCALINHO',
      'CLÁUDIA',
      'CASTANHEIRA',
      'CARLINDA',
      'CANARANA',
      'CANABRAVA DO NORTE',
      'CAMPO VERDE',
      'CAMPINÁPOLIS',
      'BRASNORTE',
      'BOM JESUS DO ARAGUAIA',
      'BARRA DO GARÇAS',
      'ARIPUANÃ',
      'ARAGUAINHA',
      'ARAGUAIANA',
      'APIACÁS',
      'ALTO TAQUARI',
      'ALTO GARÇAS',
      'ALTO BOA VISTA',
      'ALTO ARAGUAIA',
      'ALTA FLORESTA',
      'ÁGUA BOA',
    ],
  },
  {
    ddd: '65',
    state: 'MT',
    cities: [
      'CURVELANDIA',
      'CONQUISTA DO OESTE',
      'NOVA MARILÂNDIA',
      'VÁRZEA GRANDE',
      'VALE DE SÃO DOMINGOS',
      'TANGARÁ DA SERRA',
      'SAPEZAL',
      'SANTO ANTÔNIO DO LEVERGER',
      'SANTA RITA DO TRIVELATO',
      'SALTO DO CÉU',
      'ROSÁRIO OESTE',
      'SÃO JOSÉ DO RIO CLARO',
      'SANTO AFONSO',
      'RIO BRANCO',
      'RESERVA DO CABAÇAL',
      'SÃO JOSÉ DOS QUATRO MARCOS',
      'PORTO ESTRELA',
      'PORTO ESPERIDIÃO',
      'PONTES E LACERDA',
      'POCONÉ',
      'NOVA OLÍMPIA',
      'NOVA MUTUM',
      'NOVA LACERDA',
      'NOSSA SENHORA DO LIVRAMENTO',
      'NORTELÂNDIA',
      'NOBRES',
      "MIRASSOL D'OESTE",
      'VILA BELA DA SANTÍSSIMA TRINDADE',
      'LUCAS DO RIO VERDE',
      "LAMBARI D'OESTE",
      'JAURU',
      'JANGADA',
      'ITIQUIRA',
      'INDIAVAÍ',
      "GLÓRIA D'OESTE",
      "FIGUEIRÓPOLIS D'OESTE",
      'DIAMANTINO',
      'DENISE',
      'CUIABÁ',
      'COMODORO',
      'CHAPADA DOS GUIMARÃES',
      'CAMPOS DE JÚLIO',
      'CAMPO NOVO DO PARECIS',
      'CÁCERES',
      'BARRA DO BUGRES',
      'BARÃO DE MELGAÇO',
      'ARENÁPOLIS',
      'ARAPUTANGA',
      'ALTO PARAGUAI',
      'ACORIZAL',
    ],
  },
];

const invalidResponse = {
  type: 'ddd_error',
  message: 'DDD não encontrado',
  name: 'DDD_NOT_FOUND',
};

const invalidResponseByState = {
  type: 'ddd_error',
  message: 'DDDs não encontrados',
  name: 'DDD_NOT_FOUND',
};

module.exports = {
  validResponseV1,
  validResponseV2,
  validResponseAllDDDV1,
  validResponseDDDByStateV1,
  invalidResponse,
  invalidResponseByState,
};
