import { describe, expect, it, vi } from 'vitest';
import axios from 'axios';
import OrdinaryElections from '@/pages/api/eleicoes/ordinarias';

vi.mock('axios', () => ({
  default: {
    get: vi.fn(),
  },
}));

describe('API handler /api/eleicoes/ordinarias', () => {
  it('deve retornar a lista de eleições ordinarias', async () => {
    const mockResponse = [
      {
        id: 2045202024,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2024,
        codigo: null,
        nomeEleicao: 'Eleições Municipais 2024',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2024-10-06',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2024',
      },
      {
        id: 2040602022,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2022,
        codigo: null,
        nomeEleicao: 'Eleição Geral Federal 2022',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'F',
        dataEleicao: '2022-10-02',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2022',
      },
      {
        id: 2032002020,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2020,
        codigo: null,
        nomeEleicao: 'Eleições Municipais 2020 - AP',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2020-11-14',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2020',
      },
      {
        id: 2030402020,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2020,
        codigo: null,
        nomeEleicao: 'Eleições Municipais 2020',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2020-11-15',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2020',
      },
      {
        id: 2022802018,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2018,
        codigo: null,
        nomeEleicao: 'Eleição Geral Federal 2018',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'F',
        dataEleicao: '2018-10-07',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2018',
      },
      {
        id: 2,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2016,
        codigo: null,
        nomeEleicao: 'Eleições Municipais 2016',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2016-10-02',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2016',
      },
      {
        id: 680,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2014,
        codigo: null,
        nomeEleicao: 'Eleições Gerais 2014',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'F',
        dataEleicao: '2014-10-05',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2014',
      },
      {
        id: 1699,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2012,
        codigo: null,
        nomeEleicao: 'Eleição Municipal 2012',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2012-10-07',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2012',
      },
      {
        id: 14417,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2010,
        codigo: null,
        nomeEleicao: 'Eleições 2010',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'F',
        dataEleicao: null,
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2010',
      },
      {
        id: 14422,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2008,
        codigo: null,
        nomeEleicao: 'Eleições 2008',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: '2008-10-05',
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2008',
      },
      {
        id: 14423,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2006,
        codigo: null,
        nomeEleicao: 'Eleições 2006',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'F',
        dataEleicao: null,
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2006',
      },
      {
        id: 14431,
        siglaUF: null,
        localidadeSgUe: null,
        ano: 2004,
        codigo: null,
        nomeEleicao: 'Eleições 2004',
        tipoEleicao: 'O',
        turno: null,
        tipoAbrangencia: 'M',
        dataEleicao: null,
        codSituacaoEleicao: null,
        descricaoSituacaoEleicao: null,
        descricaoEleicao: '2004',
      },
    ];

    vi.mocked(axios.get).mockResolvedValueOnce({ data: mockResponse });

    const req = {};
    const res = {
      status: vi.fn().mockReturnThis(),
      json: vi.fn().mockReturnThis(),
      send: vi.fn().mockReturnThis(),
    };
    await OrdinaryElections(req, res);

    expect(res.status).toHaveBeenCalledWith(200);
    expect(res.json).toHaveBeenCalledWith(mockResponse);
    expect(axios.get).toHaveBeenCalled();
  });
});
