name: ESlint
on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  code:
    name: Versões NodeJS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 15.x

    steps:
      - name: Obtendo versão mais nova do Codigo
        uses: actions/checkout@v2

      - name: Configurando NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version: ${{ matrix.node-version }}

      - name: Instalar as dependências do npm
        run: npm install

      - name: Rodando ESlint
        run: npm run fix

      - name: Rodando testes
        run: npm test

      - name: NPM cache
        id: npm-cache-dir
        run: >
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: >
            ${{ runner.os }}-node-
